### PR TITLE
update ember to 3.0

### PR DESCRIPTION
**Pull request by chrisvdp**
`DEPRECATION: ember-cli-babel 5.x has been deprecated.`

### CODE REVIEW

**Comment by kagemusha** [comment]
@chrisvdp any interest in doing a full ember upgrade on this?

**Comment by chrisvdp** [comment]
pushed

**Comment by chrisvdp** [comment]
travis results from my fork https://travis-ci.org/chrisvdp/ember-deparam/builds/362255935

**Comment by kagemusha** [comment]
@chrisvdp awesome.  thanks!

**Pull request merged**
